default_platform(:ios)

platform :ios do
  before_all do
    cocoapods(try_repo_update_on_error: true)
  end

  desc "Builds and runs unit tests"
  lane :test do
    scan(scheme: 'BullsEye')
  end

  desc "Builds and runs UI tests"
  lane :ui_tests do
    scan(scheme: 'UITests')
  end
end
